name: poll release & update

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:


jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{github.token}}
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4

      - name: "check last synced version"
        id: check_version
        run: |
          last_version=$(cat .last_synced_version 2>/dev/null || echo "none")
          echo "last=$last_version" >> $GITHUB_OUTPUT

      - name: "get latest goharbor/harbor-cli release"
        id: release
        run: |
          tag=$(curl -s https://api.github.com/repos/nucleofusion/harbor-cli/releases/latest | jq -r .tag_name)
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: compare versions
        if: steps.check_version.outputs.last != steps.release.outputs.tag
        run: |
          echo "new release found: ${{ steps.release.outputs.tag }}"

      - name: downloading checksum.txt
        if: steps.check_version.outputs.last != steps.release.outputs.tag
        run: |
          gh release download ${{ steps.release.outputs.tag }} \
            --repo nucleofusion/harbor-cli \
            --pattern "checksum.txt"

      - name: extracting shasum
        if: steps.check_version.outputs.last != steps.release.outputs.tag
        id: sha
        run: |
          amd=$(grep 'harbor-cli_v[0-9.]\+_darwin_amd64\.tar\.gz' checksum.txt | awk '{print $1}')
          arm=$(grep 'harbor-cli_v[0-9.]\+_darwin_arm64\.tar\.gz' checksum.txt | awk '{print $1}')
          echo "amd=${amd}" >> $GITHUB_OUTPUT
          echo "arm=${arm}" >> $GITHUB_OUTPUT

      - name: update brew formula
        if: steps.check_version.outputs.last != steps.release.outputs.tag
        run: |
          version=${{steps.release.outputs.tag}}
          amd=${{steps.sha.outputs.amd}}
          arm=${{steps.sha.outputs.arm}}

          sed -i.bak -E \
            -e "s|(url \".*darwin_amd64\.tar\.gz\")|url \"https://github.com/nucleofusion/harbor-cli/releases/download/v${version}/harbor-cli_${version}_darwin_amd64\.tar\.gz\"|" \
            -e "0,/sha256 \".*\"/{s|sha256 \".*\"|sha256 \"${amd}\"|}" \
            -e "s|(url \".*darwin_arm64\.tar\.gz\")|url \"https://github.com/nucleofusion/harbor-cli/releases/download/v${version}/harbor-cli_${version}_darwin_arm64\.tar\.gz\"|" \
            -e "0,/sha256 \".*\"/{s|sha256 \".*\"|sha256 \"${arm}\"|}" \
            -e "s|(version \").*(\")|\1${version}\2|" \
            harbor-cli.rb

          rm -f harbor-cli.rb.bak

      - name: commit and push changes
        if: steps.check_version.outputs.last != steps.release.outputs.tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add harbor-cli.rb  
          git commit -m "updating for harbor-cli ${{ steps.release.outputs.tag }}" || echo "no changes"
          git push

